# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjam', '0002_peminjam_tipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjam',
            name='tipe',
            field=models.CharField(choices=[(b'Fakultas-Prodi', b'Fakultas-Prodi'), (b'UKA', b'UKA'), (b'UKM', b'UKM')], default=b'UKM', max_length=50),
        ),
    ]
